### ISSUE TITLE
Strange behavior with particular configuration

### ISSUE THREAD

**Issue by agrignard** [mitmedialab/CityMatrixSim#1]
When modifying the grid physically and putting a building at an intersection there is a problem in the model all The PEV get stucked at some point.

They should be "smart" enough to recompute their path and find another one.

**Comment by kalyons11** [comment]
I see. So you are directly editing the grid and placing a building at an intersection.

Do all of the PEV's get stuck, or just some of them?

**Comment by agrignard** [comment]
I have to double check they seems quiet stuck all of them

**Comment by agrignard** [comment]
Actually it might be link to issue #2 it seems ok now.

However with surround set to false it should work also no?

**Comment by kalyons11** [comment]
Yes, it should work without the surrounding road too. We can take a look tomorrow to see where it went wrong.

**Comment by popabczhang** [comment]
Is the problem happening in "Dynamic Grid Editing" mode or even in static mode?

**Comment by agrignard** [comment]
dynamic one

**Comment by kalyons11** [comment]
I just ran the online grid on my machine. This is what I am seeing.

![image](https://cloud.githubusercontent.com/assets/20310471/23006482/10df0842-f3d0-11e6-84cf-01b9fd6e78c3.png)

As you can see, we have a road segment that is not accessible by any other segment. Thus, when a PEV sets its target to enter the segment, it is unable to proceed and stops.

My latest commit adds a check to see if this occurs. If we have a null path to a target, I simply stop the simulation and return it as a "bad configuration."

**Is this the behavior we want?**

**Comment by agrignard** [comment]
yes i think its a good behavior. I agree this is not a "valid" city configuration but a user might design this
