### ISSUE TITLE
Make the external road visible

### ISSUE THREAD

**Issue by agrignard** [mitmedialab/CityMatrixSim#2]
The actual road are actually in black maybe it makes sense to display them as normal road in gray?

**Comment by kalyons11** [comment]
![image](https://cloud.githubusercontent.com/assets/20310471/22986977/49df91ac-f37b-11e6-92e7-6bac7d924fbc.png)

This is what I can see for the surrounding road. Isn't that the same color as all the other roads?

**Comment by agrignard** [comment]
I have this 
<img width="580" alt="screen shot 2017-02-15 at 12 55 58" src="https://cloud.githubusercontent.com/assets/3928502/22987832/28849324-f37e-11e6-8efc-b9df7bae5dea.png">

**Comment by kalyons11** [comment]
Did you turn on the surrounding road parameter to true? It should be there.

On Feb 15, 2017, at 12:56 PM, Arnaud Grignard <notifications@github.com<mailto:notifications@github.com>> wrote:


I have this
[screen shot 2017-02-15 at 12 55 58]<https://cloud.githubusercontent.com/assets/3928502/22987832/28849324-f37e-11e6-8efc-b9df7bae5dea.png>

**Comment by agrignard** [comment]
oh you 're right it was false.
