### ISSUE TITLE
Fix cell update methods to be simpler

### ISSUE THREAD

**Issue by kalyons11** [mitmedialab/CityMatrixSim#21]
Our current code to update cell values could be improved. Currently, we call `cell.update_pop()` and `cell.update_height()` to fix these parameters after a density/index change, as seen [here](https://github.com/mitmedialab/CityMatrixSim/blob/solar/global/cityiograph.py#L232).

Instead, we should define an `@property` for `cell.height` and `cell.population` (see [here](https://www.programiz.com/python-programming/property)) to make this process more robust. That way, we never have to explicitly call these other methods and potentially forget to do it at a particular time.

This should be an easy fix for a good programming practice. Let me know your thoughts!

**Comment by A-lxe** [comment]
Yeah good idea! I can pop it in tonight.

**Comment by kalyons11** [comment]
Fixed this issue with commit 68a36e8. Closing.
