### ISSUE TITLE
Parse "metrics" and "score" dict in new JSON format

### ISSUE THREAD

**Issue by popabczhang** [mitmedialab/CityMatrixSim#22]
@kalyons11 

Please update the server to parse "metrics" and "score" dict in new JSON format. 

I have already updated it in GH CV: 

![metrics json format](https://user-images.githubusercontent.com/2801912/27813500-6cf7d95c-6044-11e7-9c11-34f230d672ca.PNG)

**Comment by kalyons11** [comment]
Fixed this issue with commit b97b5fb. Closing.
