### ISSUE TITLE
"Give me another suggestion/Next suggestion" button

### ISSUE THREAD

**Issue by popabczhang** [mitmedialab/CityMatrixSim#25]
@kalyons11 

When AIStep == 20, toggle 1 on the table can be used as "Next Suggestion" button. 

By comparing previous "toggle1" value with the current one, we can know if the user is asking for another AI suggestion. 

@A-lxe 

Please help Kevin on how to keep a queue of suggested AIMov, and give the user the next best suggestion when requested by the user via toggle 1. 

Thanks!

**Comment by kalyons11** [comment]
I have implemented an early version of this new feature with e010140. But, what I am seeing is that the AI settles in on a "local optimum" in the search. For instance, it continues to recommend the same density change, just with a minor change in the value. Here is an example of the AI move queue...

```
{('DENSITY', 4, 7), ('DENSITY', 4, 8), ('DENSITY', 4, 9), ('DENSITY', 4, 11)}
```

Certainly, this is not that informative for the user.

@popabczhang @A-lxe Do you have any thoughts on how to resolve? We can be stricter about our search to avoid these conditions...?

**Comment by popabczhang** [comment]
Great insight. When we create a "suggested" queue, let's don't include the value as key for density AIMov: 
('DENSITY', idx)
For cell AIMov, seems it's fine: 
('CELL', x, y, id)
Will that work?

**Comment by kalyons11** [comment]
This should work! Let me implement now and get back to you.

**Comment by kalyons11** [comment]
Even with this change, the search still reaches the `lmt` value in the inner search while loop. Thus, it still suggests `('DENSITY', 4)` for this city as the move...

**Comment by popabczhang** [comment]
Let's leave it for now if it still gives the same density move when reach limit. 
I will explain to them. In the future, we can raise a flag and then let AI "explain" this issue vocally. 
Thanks!
