### ISSUE TITLE
Branch cleanup needed.

### ISSUE THREAD

**Issue by kalyons11** [mitmedialab/CityMatrixSim#26]
We should do a branch update/master merge soon. As I understand, the `analysis` branch has a lot of the latest code. We should get back to a single working branch, then move from there if we need to again soon.

**Comment by popabczhang** [comment]
correct. analysis branch is the most current. I will do some final adjustments to make it work with gh and unity (if necessary) and then merge it to master branch.

**Comment by popabczhang** [comment]
merged "analysis" to "master" closing. @kalyons11, you can decide if you would like to delete the analysis branch.
