### ISSUE TITLE
GAMA Traffic Batch Simulation Issues

### ISSUE THREAD

**Issue by kalyons11** [mitmedialab/CityMatrixSim#29]
*Creating a new issue for this bug thread, which began in commit ce42bd7.*

<hr/>

@popabczhang 

1. I am struggling to fix that bug you mentioned in the batch simulation. Gama does not have great documentation when it comes to catching errors in their simulation script. Perhaps you could loop in @agrignard for me? Also, do you have a more specific stack trace or the file that crashed it?

     I also created a post on the GAMA forum to try and get some support.

2. We also have the issue with the traffic pattern only being in one direction.

     First, I tried changing the search algorithm the PEV's use in the grid. The four available search algorithms in the current GAMA build are given by: `["A*", "Dijkstra", "JPS", "BF"]`.

     Here are my results.

     ![image](https://user-images.githubusercontent.com/20310471/28100652-68713a06-6691-11e7-8ce3-9a39d73ece0f.png)

     ![image](https://user-images.githubusercontent.com/20310471/28100695-b7998020-6691-11e7-8067-2849a629dbda.png)

     ![image](https://user-images.githubusercontent.com/20310471/28100773-2de603ca-6692-11e7-8ca5-b2c001af3cda.png)

     ![image](https://user-images.githubusercontent.com/20310471/28100845-a8dc6fb0-6692-11e7-8126-c5e94606465d.png)

     **So, clearly this is not the issue.**

     It may be an issue with the `neighborhood` parameter on the `grid` object and how I assign the traffic values during the simulation. This is where I am looking next...

## Do you have any additional thoughts?

Thanks,

Kevin

**Comment by popabczhang** [comment]
Due to the limited time we have now, let's focus on the second issue for now. I will try to loop in Arnaud tomorrow! Thanks.

**Comment by agrignard** [comment]
Hi Guys,

Let me know if you need any GAMA helps. I know Ryan is very busy for his
thesis that's why I don't interfere that much to avoid noise but we can
meet if needed

Arnaud

**Comment by agrignard** [comment]
@popabczhang I am not sure I saw the forum issue on GAMA, where did you post it? Did you use the issue tracker here ?

https://github.com/gama-platform/gama/issues

**Comment by kalyons11** [comment]
@agrignard I tried to post on the Forum twice last night but I'm not sure if it went through...

Anyway, do you know GAMA has a native `try` / `except` functionality to keep the simulation from crashing when an error is encountered? You can see the error that we are getting [**here**](https://github.com/mitmedialab/CityMatrixSim/commit/ce42bd7ed5ab5d4a857656abd43bf1a91beb78f2#commitcomment-23030973).

**Comment by popabczhang** [comment]
@agrignard Thanks for being considerate on the "non-interfere". 
While now we do need some help on GAMA from you! 
The first priority now is figuring out why the simulation result is very much "one directional". 
@kalyons11 @agrignard , shall we have a meeting tomorrow? Kavin is working, so maybe an in-person meeting in the late afternoon or Skype meeting at noon or night? 
Thank you!

**Comment by popabczhang** [comment]
I'm moving the relevant information from comments to here: 

"
Here are three simulated results. All X direction roads have much more traffic than Y direction ones. 
![image](https://user-images.githubusercontent.com/2801912/28068639-65712d5c-6614-11e7-8e02-8d7e2255bf44.png)
![image](https://user-images.githubusercontent.com/2801912/28068746-d94fc24c-6614-11e7-81bf-2b352172884c.png)
![image](https://user-images.githubusercontent.com/2801912/28068771-edec75ba-6614-11e7-9856-46d15fe652b7.png)
"

**Comment by agrignard** [comment]
@Kevisn did you try with other shortest path algorithm?

Also do you think you can retest it with the very last version of GAMA (I
know that some optimization have been made this mont on the shortes path
algo. Also it's possible to choose which one si it might solve the problem
(by default it's A* but we could try with Dijkstra

**Comment by agrignard** [comment]
This is strange i gave the model to a coleague and he doesn t have this
strange resuls.

Can you detailed how to reproduce it?

Le jeu. 13 juil. 2017 à 07:18, Kevin Lyons <notifications@github.com> a
écrit :

**Comment by kalyons11** [comment]
@agrignard We just ran the `CityGamatrix_PEV.gaml` file with the `Display` experiment. This resulted in the odd output that Ryan indicated above.

**Comment by agrignard** [comment]
yep indeed... we are working on that with one of my fried /colleagues of
the GAMA team but we didn't figure it out.

**Comment by agrignard** [comment]
the problem is that he is in vietnam so is now sleeping... so I don't think
I have any new input before 4... maybe we cna postpose th emeeting if we
have no solution? I think it's in the pipe on the GAMA side I hope it
shoudl be fixed soon

**Comment by agrignard** [comment]
actually I am not sure to really understand the problem it makes sense that
at the end people are more using the road on the middle no?

**Comment by popabczhang** [comment]
Yes. The people at the end should use the road in the middle. So the roads in the middle shall have higher traffic volume. But the issue here is that only roads in x direction are getting volume, in contrast, roads in y direction are not getting volume, no matter the distribution of the population.  

I suggest that we still have a quick meeting today at 4 pm to get on the same page for the issue? Thanks in advance!

**Comment by kalyons11** [comment]
Yes, I will still be there!

**Comment by kalyons11** [comment]
Fixed in fef8851. Closing!
