### ISSUE TITLE
Error Isolated in a city

### ISSUE THREAD

**Issue by popabczhang** [mitmedialab/CityMatrixSim#30]
Error message: 
![screenshot 2017-07-13 22 14 23](https://user-images.githubusercontent.com/2801912/28195540-d9caaa88-6818-11e7-92d6-fd98aef74ba7.png)

Input city JSON: 
https://www.dropbox.com/s/rk5y9nanxrin7ui/SolarSimCity_4025.json?dl=0

**Comment by kalyons11** [comment]
@popabczhang Since you were able to complete the training, is it still critical to try to debug these GAMA related errors?

After speaking with Arnaud, it seems it will be very difficult to `catch` these errors during runtime.

Let me know your thoughts on this!

- Kevin

**Comment by popabczhang** [comment]
Nope, thanks! Closing.
