### ISSUE TITLE
CityMatrix_PEV not running

### ISSUE THREAD

**Issue by agrignard** [mitmedialab/CityMatrixSim#4]
the current PEV version does not work because it s waiting for an input_dir that does not exists in the git in the batch mode.

By default we should always have a working version. Maybe we can put some very generic files at least. We don t want to put all of them for sure.

**Comment by kalyons11** [comment]
Good point! I have added new general input and output folders to repository in my [latest commit](https://github.com/mitmedialab/CityMatrixSim/commit/cb6d3ae39f873a8cd1bf526863fb97ed464b71da). Closing this issue.
