### ISSUE TITLE
"Display" and "Run" for model Citygamatrix_PEV failed to output correct json filename

### ISSUE THREAD

**Issue by popabczhang** [mitmedialab/CityMatrixSim#5]
"Display" and "Run" for model Citygamatrix_PEV failed to output correct json filename. 
The JSON file name is "null_output.json"

**Comment by kalyons11** [comment]
My latest commit fixes this issue. Closing.

**Comment by popabczhang** [comment]
Cool thanks

**Comment by popabczhang** [comment]
Just did a simple fix again. The previous fix still doesn't work on Single Run somehow.
