### ISSUE TITLE
all traffic and wait output values are 0 for "city_1_output.json" under "machine_1.zip"

### ISSUE THREAD

**Issue by popabczhang** [mitmedialab/CityMatrixSim#6]
all traffic and wait output values are 0 for "city_1_output.json" under "machine_1.zip"

in "city_1_output.json" file, all road cell has following all-zero data. 
"data":{"traffic":0,"wait":0}

other cities doesn't seem like this.

**Comment by kalyons11** [comment]
I noticed the same thing - could this have just been a bad simulation run?

**Comment by popabczhang** [comment]
![image](https://cloud.githubusercontent.com/assets/2801912/24026685/5f1c0994-0a99-11e7-977b-9af5acc2e411.png)
Might be, above is the city. not a good city for sure. but in display mode it still accumulation heatmap values. Why doesn't it save to output json?

**Comment by kalyons11** [comment]
Really not sure. All of the other files seem to have normal outputs. The only thing I could see would be an issue writing to the file since this was the first city in the batch?

**Comment by popabczhang** [comment]
I single-run other cities, although the output filename is wrong ("null_output".json), the values are normal. So I don't think if it was the first city matters. BTW, city_0 is the first city in batch.

**Comment by kalyons11** [comment]
Really not sure then... it should just take the values in the simulation and stick them in the JSON!

**Comment by popabczhang** [comment]
Maybe let's just ignore it for now.
