### ISSUE TITLE
for CityGamatrix_Visual.gaml, the screenshots has the first one duplicated and last one missing

### ISSUE THREAD

**Issue by popabczhang** [mitmedialab/CityMatrixSim#7]
for CityGamatrix_Visual.gaml, if we run 10 output.json, from city_0 to city_9. The screenshots will have the first two duplicated and last one missing, which means both first and second screenshot as city_0's "city" screenshot, but the last one -- city_9's "wait" screenshot -- missing.

**Comment by kalyons11** [comment]
Going to bed now, but I will make a fix for this tomorrow. Thanks for finding this bug!

**Comment by kalyons11** [comment]
I just ran the visualization script on my machine and it worked perfectly - 3 screenshots per city with no edge issues as you're mentioning. Could you please send the example?

**Comment by popabczhang** [comment]
I guess it's again due to the windows filename format. Let's ignore for now then.
