### ISSUE TITLE
simualtion crashes after 1 day

### ISSUE THREAD

**Issue by agrignard** [mitmedialab/CityMatrixSim#9]
After 1 day (8000ish iteration) there is an error thrown in the default model.

**Comment by kalyons11** [comment]
Did you record or take a screenshot of this error? And this is in CityGamatrix_PEV?

**Comment by popabczhang** [comment]
Memory leak?



--
YAN ZHANG "RYAN"


MASTER'S DEGREE CANDIDATE, ASSISTANT RESEARCHER
MEDIA ARTS & SCIENCES, MEDIA LAB
MASSACHUSETTS INSTITUTE OF TECHNOLOGY

M.S. ADVANCED ARCHITECTURE DESIGN
COLUMBIA UNIVERSITY IN THE CITY OF NEW YORK

20 AMES STREET, BUILDING E15-368
CAMBRIDGE, MA 02142

1(917)767-3589
POPABCZHANG@GMAIL.COM

**Comment by kalyons11** [comment]
Perhaps... let me run the simulation on my machine again and take a look.

**Comment by kalyons11** [comment]
I just ran it for a day on my end and everything ran smoothly. @agrignard could you try to replicate this and send the crash error?

**Comment by kalyons11** [comment]
@agrignard - were you ever able to replicate this issue? If not, can we close this on GitHub? Thanks!

**Comment by agrignard** [comment]
yes the problem is still here. it crashes after 8658 cycles which is one day.
I have the current version of the CityGamatrix.

@kalyons11  Does it work on your computer ?
<img width="1920" alt="screen shot 2017-04-17 at 17 41 42" src="https://cloud.githubusercontent.com/assets/3928502/25105992/33dd2ec4-2395-11e7-8f13-f008d2fe8070.png">

**Comment by agrignard** [comment]
1 occurence in Simulation 0 at cycle 8641: Java error: I/O error
in save copy ;
IOException: No such file or directory
java.io.UnixFileSystem.createFileExclusively(Native Method)
java.io.File.createNewFile(File.java:1012)
msi.gama.util.file.GamaJsonFile.flushBuffer(GamaJsonFile.java:126)
msi.gama.util.file.GamaFile.save(GamaFile.java:475)
msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:257)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
in save copy ;
in agent Simulation 0

**Comment by kalyons11** [comment]
Aha, this might be an error when it tries to output the JSON for that simulation day. If you look at the  `output_dir` variable at the top of `CityGamatrix_PEV.gaml`, make sure that this relative path is one that actually exists on your machine. You may have to create an output folder if not. Otherwise, you will get this Java I/O error.

Let me know if that helps!

**Comment by agrignard** [comment]
yep but by default any model on the github should work by themselves... so I just added a general_output folder in the github so the model can run

So now the simualtion stop (but not crashes) is it normal? Would it be possible to have a mode where the simualtion is always running?

**Comment by kalyons11** [comment]
Yes, we already have this feature in place. If you set the "Continuous Demo" parameter to be true (or the `looping` boolean in `CityGamatrix.gaml`), the simulation will continue to run indefinitely.

**Comment by agrignard** [comment]
ok perfect. So I close this issue
